---
  functions:
    "*comp.VmBase":
      Event:
        descr: Current event
      CompByCr:
        descr: Returns component by its reference
        params:
          - name: compReference
            valueCompleter:
              yamlPathCompleter:
                self: yes
                pathExpr: "[%].cr:value"
                quote: '"'
    "*comp.CompRuntimeSW":
      LoadUnit:
        descr: Loads an unit
        params:
          - name: "unit name"
            valueCompleter:
              fileNameCompleter:
                folderPrefix: unit
                trimSuffix: .yaml
                quote: '"'
      GetProp:
        descr: Get component property
        params:
          - name: "property name"
            valueCompleter:
              yamlPathCompleter:
                self: yes
                pathExpr: "unitInterface.properties.%$"
                pathNodes: yes
                quote: '"'
      HasProp:
        descr: returns true if property defined
        params:
          - name: "property name"
            valueCompleter:
              yamlPathCompleter:
                self: yes
                pathExpr: "unitInterface.properties.%$"
                pathNodes: yes
                quote: '"'
    "*comp.EventRuntime":
      ReloadUnit:
        descr: Reloads current unit
      LoadUnit:
        descr: Loads an unit
        params:
          - name: "unit name"
            valueCompleter:
              fileNameCompleter:
                folderPrefix: unit
                trimSuffix: .yaml
                quote: '"'
    "comp.ITable":
      GroupBy:
        descr: Rearranges table rows grouping them by col
        params:
          - name: "group by column"
          - name: "groups sublist column"
    "*store.DatabaseContext":
      CreateDBO:
        descr: Creates database object
        params:
          - name: "data"
          - name: "tableName"
            valueCompleter:
              fileNameCompleter:
                folderPrefix: dcfg/schema
                trimSuffix: .yaml
                quote: '"'
