---
  functions:
    "*comp.VmBase":
      Event:
        descr: Current event
      CompByCr:
        descr: Returns component by its reference
        params:
          - name: compReference
            valueCompleter: yamlPathCompleter
            valueCompleterParams:
              self: yes
              pathExpr: "[%].cr:value"
              quote: '"'
    "*comp.EventRuntime":
      ReloadUnit:
        descr: Reloads current unit
      LoadUnit:
        descr: Loads an unit
        params:
          - name: "unit name"
            valueCompleter: fileNameCompleter
            valueCompleterParams:
              folderPrefix: unit
              trimSuffix: .yaml
              quote: '"'
    "comp.ITable":
      GroupBy:
        descr: Rearranges table rows grouping them by col
        params:
          - name: "group by column"
          - name: "groups sublist column"
